// <auto-generated />
using Aryaans_Hotel_Booking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aryaans_Hotel_Booking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250529203413_InitialModelSetup")]
    partial class InitialModelSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Aryaans_Hotel_Booking.Data.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<double?>("ReviewScore")
                        .HasColumnType("REAL");

                    b.Property<int>("StarRating")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "New York",
                            Country = "USA",
                            ImagePath = "/images/hotels/grand_hyatt.jpg",
                            Name = "Grand Hyatt",
                            PricePerNight = 300.00m,
                            ReviewScore = 8.8000000000000007,
                            StarRating = 5
                        },
                        new
                        {
                            Id = 2,
                            City = "New York",
                            Country = "USA",
                            ImagePath = "/images/hotels/the_plaza.jpg",
                            Name = "The Plaza",
                            PricePerNight = 500.00m,
                            ReviewScore = 9.1999999999999993,
                            StarRating = 5
                        });
                });

            modelBuilder.Entity("Aryaans_Hotel_Booking.Data.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("HotelId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            Description = "Spacious room with a king-sized bed and city view.",
                            HotelId = 1,
                            PricePerNight = 450.00m,
                            RoomType = "Deluxe King"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 2,
                            Description = "Comfortable room with a queen-sized bed.",
                            HotelId = 1,
                            PricePerNight = 350.00m,
                            RoomType = "Standard Queen"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 4,
                            Description = "Luxurious suite with a separate living area and premium amenities.",
                            HotelId = 2,
                            PricePerNight = 799.99m,
                            RoomType = "Plaza Suite"
                        });
                });

            modelBuilder.Entity("Aryaans_Hotel_Booking.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Aryaans_Hotel_Booking.Data.Entities.Room", b =>
                {
                    b.HasOne("Aryaans_Hotel_Booking.Data.Entities.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Aryaans_Hotel_Booking.Data.Entities.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
